### ISSUE TITLE
Error on Adding "Preview Image (Media)" as a column

### ISSUE THREAD

**Issue by artistro08** [jan-vince/smallrecords#95]
Today, I added a "Preview Image (Media)" to the column of one of the lists I created. 

I now get this error: 
```
Symfony\Component\Debug\Exception\FatalThrowableError: Object of class Illuminate\Routing\UrlGenerator could not be converted to string in /var/www/html/procedural-tech/plugins/janvince/smallrecords/Plugin.php:218
```

Stack Trace: 

```Symfony\Component\Debug\Exception\FatalThrowableError: Object of class Illuminate\Routing\UrlGenerator could not be converted to string in /var/www/html/procedural-tech/plugins/janvince/smallrecords/Plugin.php:218
Stack trace:
#0 [internal function]: JanVince\SmallRecords\Plugin->JanVince\SmallRecords\{closure}()
#1 /var/www/html/procedural-tech/modules/backend/widgets/Lists.php(1285): call_user_func_array()
#2 /var/www/html/procedural-tech/modules/backend/widgets/Lists.php(1155): Backend\Widgets\Lists->evalCustomListType()
#3 /var/www/html/procedural-tech/modules/backend/widgets/liststructure/partials/_list_body_row.htm(50): Backend\Widgets\Lists->getColumnValue()
#4 /var/www/html/procedural-tech/modules/system/traits/ViewMaker.php(252): include('/var/www/html/p...')
#5 /var/www/html/procedural-tech/modules/system/traits/ViewMaker.php(99): Backend\Classes\WidgetBase->makeFileContents()
#6 /var/www/html/procedural-tech/modules/backend/widgets/liststructure/partials/_list_body_rows.htm(2): Backend\Classes\WidgetBase->makePartial()
#7 /var/www/html/procedural-tech/modules/system/traits/ViewMaker.php(252): include('/var/www/html/p...')
#8 /var/www/html/procedural-tech/modules/system/traits/ViewMaker.php(99): Backend\Classes\WidgetBase->makeFileContents()
#9 /var/www/html/procedural-tech/modules/backend/widgets/liststructure/partials/_list.htm(29): Backend\Classes\WidgetBase->makePartial()
#10 /var/www/html/procedural-tech/modules/system/traits/ViewMaker.php(252): include('/var/www/html/p...')
#11 /var/www/html/procedural-tech/modules/system/traits/ViewMaker.php(99): Backend\Classes\WidgetBase->makeFileContents()
#12 /var/www/html/procedural-tech/modules/backend/widgets/lists/partials/_list-container.htm(2): Backend\Classes\WidgetBase->makePartial()
#13 /var/www/html/procedural-tech/modules/system/traits/ViewMaker.php(252): include('/var/www/html/p...')
#14 /var/www/html/procedural-tech/modules/system/traits/ViewMaker.php(99): Backend\Classes\WidgetBase->makeFileContents()
#15 /var/www/html/procedural-tech/modules/backend/widgets/Lists.php(238): Backend\Classes\WidgetBase->makePartial()
#16 /var/www/html/procedural-tech/modules/backend/behaviors/listcontroller/partials/_container.htm(10): Backend\Widgets\Lists->render()
#17 /var/www/html/procedural-tech/modules/system/traits/ViewMaker.php(252): include('/var/www/html/p...')
#18 /var/www/html/procedural-tech/modules/backend/classes/ControllerBehavior.php(140): Backend\Classes\Controller->makeFileContents()
#19 /var/www/html/procedural-tech/modules/system/traits/ViewMaker.php(99): Backend\Classes\ControllerBehavior->makeFileContents()
#20 /var/www/html/procedural-tech/modules/backend/behaviors/ListController.php(436): Backend\Classes\ControllerBehavior->makePartial()
#21 /var/www/html/procedural-tech/modules/backend/behaviors/ListController.php(423): Backend\Behaviors\ListController->listMakePartial()
#22 /var/www/html/procedural-tech/vendor/october/rain/src/Extension/ExtendableTrait.php(435): Backend\Behaviors\ListController->listRender()
#23 /var/www/html/procedural-tech/vendor/october/rain/src/Extension/Extendable.php(46): October\Rain\Extension\Extendable->extendableCall()
#24 /var/www/html/procedural-tech/plugins/janvince/smallrecords/controllers/records/index.htm(1): October\Rain\Extension\Extendable->__call()
#25 /var/www/html/procedural-tech/modules/system/traits/ViewMaker.php(252): include('/var/www/html/p...')
#26 /var/www/html/procedural-tech/modules/system/traits/ViewMaker.php(113): Backend\Classes\Controller->makeFileContents()
#27 /var/www/html/procedural-tech/modules/backend/classes/Controller.php(397): Backend\Classes\Controller->makeView()
#28 /var/www/html/procedural-tech/modules/backend/classes/Controller.php(255): Backend\Classes\Controller->execPageAction()
#29 /var/www/html/procedural-tech/modules/backend/classes/BackendController.php(143): Backend\Classes\Controller->run()
#30 /var/www/html/procedural-tech/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Backend\Classes\BackendController->run()
#31 /var/www/html/procedural-tech/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction()
#32 /var/www/html/procedural-tech/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch()
#33 /var/www/html/procedural-tech/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController()
#34 /var/www/html/procedural-tech/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Route->run()
#35 /var/www/html/procedural-tech/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#36 /var/www/html/procedural-tech/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#37 /var/www/html/procedural-tech/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#38 /var/www/html/procedural-tech/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#39 /var/www/html/procedural-tech/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#40 /var/www/html/procedural-tech/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#41 /var/www/html/procedural-tech/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle()
#42 /var/www/html/procedural-tech/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#43 /var/www/html/procedural-tech/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#44 /var/www/html/procedural-tech/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#45 /var/www/html/procedural-tech/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#46 /var/www/html/procedural-tech/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#47 /var/www/html/procedural-tech/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then()
#48 /var/www/html/procedural-tech/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack()
#49 /var/www/html/procedural-tech/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute()
#50 /var/www/html/procedural-tech/vendor/october/rain/src/Router/CoreRouter.php(31): Illuminate\Routing\Router->dispatchToRoute()
#51 /var/www/html/procedural-tech/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): October\Rain\Router\CoreRouter->dispatch()
#52 /var/www/html/procedural-tech/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#53 /var/www/html/procedural-tech/plugins/offline/responsiveimages/classes/ResponsiveImagesMiddleware.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#54 /var/www/html/procedural-tech/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): OFFLINE\ResponsiveImages\Classes\ResponsiveImagesMiddleware->handle()
#55 /var/www/html/procedural-tech/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#56 /var/www/html/procedural-tech/vendor/october/rain/src/Foundation/Http/Middleware/CheckForMaintenanceMode.php(23): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#57 /var/www/html/procedural-tech/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): October\Rain\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#58 /var/www/html/procedural-tech/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#59 /var/www/html/procedural-tech/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then()
#60 /var/www/html/procedural-tech/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#61 /var/www/html/procedural-tech/index.php(54): Illuminate\Foundation\Http\Kernel->handle()
#62 {main}
```

I'm on OctoberCMS 2.1.27

Any idea of what might be causing this?

**Comment by jan-vince** [comment]
Hi, this could be caused by some changes in October 2.

I still do not use it so I can't replicate this problem.

Will look at this when I switch to OC2.

Thanks for the issue!

**Comment by artistro08** [comment]
No problem! If I figure it out, I'll make a pull request
